### ISSUE TITLE
gfal2 behaves differently between "https" and "davs"

### ISSUE THREAD

**Issue by andrearendina** [cern-fts/gfal2#16]
Dear all,

at INFN-T1 we are experiencing the following behaviour with gfal 2.21.4.
Managing a StoRM WebDAV storage element in only-write mode, we noticed a different behaviour of gfal2 between the https protocol and the davs one.

In fact, with the davs protocol the local file uploads, for instance
gfal-copy check.sh davs://xs-606.cr.cnaf.infn.it:8443/muone-tape/test-andrea-2607,
work well:

```
131.154.193.196 8443 "bddf1bbc-474f-48d5-936e-6e18729c4427@https://iam-t1-computing.cloud.cnaf.infn.it/" 2023-07-26T11:12:41.874Z "b23d9aaf-0fa6-43ea-b9de-6e16feb6276d" "PROPFIND /muone-tape/test-andrea-2607 HTTP/1.1" 404 79 12
131.154.193.196 8443 "bddf1bbc-474f-48d5-936e-6e18729c4427@https://iam-t1-computing.cloud.cnaf.infn.it/" 2023-07-26T11:12:41.896Z "-" "HEAD /muone-tape/test-andrea-2607 HTTP/1.1" 403 0 4
131.154.193.196 8443 "bddf1bbc-474f-48d5-936e-6e18729c4427@https://iam-t1-computing.cloud.cnaf.infn.it/" 2023-07-26T11:12:41.936Z "e362adbe-ef78-47c9-9d3b-a605407a18b6" "PROPFIND /muone-tape/test-andrea-2607 HTTP/1.1" 404 79 2
131.154.193.196 8443 "bddf1bbc-474f-48d5-936e-6e18729c4427@https://iam-t1-computing.cloud.cnaf.infn.it/" 2023-07-26T11:12:41.954Z "-" "HEAD /muone-tape/test-andrea-2607 HTTP/1.1" 403 0 3
131.154.193.196 8443 "bddf1bbc-474f-48d5-936e-6e18729c4427@https://iam-t1-computing.cloud.cnaf.infn.it/" 2023-07-26T11:12:41.989Z "6ce0a01c-51e8-44e0-b6c5-48ebdb904942" "PROPFIND /muone-tape/test-andrea-2607 HTTP/1.1" 404 79 2
131.154.193.196 8443 "bddf1bbc-474f-48d5-936e-6e18729c4427@https://iam-t1-computing.cloud.cnaf.infn.it/" 2023-07-26T11:12:42.017Z "-" "HEAD /muone-tape/test-andrea-2607 HTTP/1.1" 403 0 3
131.154.193.196 8443 "bddf1bbc-474f-48d5-936e-6e18729c4427@https://iam-t1-computing.cloud.cnaf.infn.it/" 2023-07-26T11:12:42.061Z "a2d092c7-617b-4f46-9f66-dea838921366" "PUT /muone-tape/test-andrea-2607 HTTP/1.1" 201 0 4 
```

Whereas with the https protocol the uploads fail:

```
131.154.193.196 8443 "bddf1bbc-474f-48d5-936e-6e18729c4427@https://iam-t1-computing.cloud.cnaf.infn.it/" 2023-07-26T11:13:58.044Z "77b293b9-9570-4bbf-8b70-d2ef6984c332" "PROPFIND /muone-tape/test-andrea-2607 HTTP/1.1" 404 79 2
131.154.193.196 8443 "bddf1bbc-474f-48d5-936e-6e18729c4427@https://iam-t1-computing.cloud.cnaf.infn.it/" 2023-07-26T11:13:58.061Z "-" "HEAD /muone-tape/test-andrea-2607 HTTP/1.1" 403 0 3
131.154.193.196 8443 "bddf1bbc-474f-48d5-936e-6e18729c4427@https://iam-t1-computing.cloud.cnaf.infn.it/" 2023-07-26T11:13:58.085Z "-" "HEAD /muone-tape/test-andrea-2607 HTTP/1.1" 403 0 3
131.154.193.196 8443 "bddf1bbc-474f-48d5-936e-6e18729c4427@https://iam-t1-computing.cloud.cnaf.infn.it/" 2023-07-26T11:13:58.107Z "-" "HEAD /muone-tape/test-andrea-2607 HTTP/1.1" 403 0 2
131.154.193.196 8443 "bddf1bbc-474f-48d5-936e-6e18729c4427@https://iam-t1-computing.cloud.cnaf.infn.it/" 2023-07-26T11:13:58.144Z "fad89005-86ba-4b49-8e90-a2b3677c8f9e" "PROPFIND /muone-tape/test-andrea-2607 HTTP/1.1" 404 79 2
131.154.193.196 8443 "bddf1bbc-474f-48d5-936e-6e18729c4427@https://iam-t1-computing.cloud.cnaf.infn.it/" 2023-07-26T11:13:58.156Z "-" "HEAD /muone-tape/test-andrea-2607 HTTP/1.1" 403 0 2
131.154.193.196 8443 "bddf1bbc-474f-48d5-936e-6e18729c4427@https://iam-t1-computing.cloud.cnaf.infn.it/" 2023-07-26T11:13:58.178Z "-" "HEAD /muone-tape/test-andrea-2607 HTTP/1.1" 403 0 2
131.154.193.196 8443 "bddf1bbc-474f-48d5-936e-6e18729c4427@https://iam-t1-computing.cloud.cnaf.infn.it/" 2023-07-26T11:13:58.200Z "-" "HEAD /muone-tape/test-andrea-2607 HTTP/1.1" 403 0 3
131.154.193.196 8443 "bddf1bbc-474f-48d5-936e-6e18729c4427@https://iam-t1-computing.cloud.cnaf.infn.it/" 2023-07-26T11:13:58.226Z "0e464398-bf91-4df7-b75a-f3d4076ad3b5" "PROPFIND /muone-tape/test-andrea-2607 HTTP/1.1" 404 79 2
131.154.193.196 8443 "bddf1bbc-474f-48d5-936e-6e18729c4427@https://iam-t1-computing.cloud.cnaf.infn.it/" 2023-07-26T11:13:58.239Z "-" "HEAD /muone-tape/test-andrea-2607 HTTP/1.1" 403 0 3
131.154.193.196 8443 "bddf1bbc-474f-48d5-936e-6e18729c4427@https://iam-t1-computing.cloud.cnaf.infn.it/" 2023-07-26T11:13:58.267Z "-" "HEAD /muone-tape/test-andrea-2607 HTTP/1.1" 403 0 2
131.154.193.196 8443 "bddf1bbc-474f-48d5-936e-6e18729c4427@https://iam-t1-computing.cloud.cnaf.infn.it/" 2023-07-26T11:13:58.292Z "-" "HEAD /muone-tape/test-andrea-2607 HTTP/1.1" 403 0 2 
```

As you can see from the logs above, it is correct that the HEAD requests fail, but with davs protocol gfal performs a PUT command anyway and the copy successes.

Is this expecetd?
How does the gfal workflow change according to the protocol?

Thank you,
cheers,
Andrea

**Comment by andrearendina** [comment]
Hi all,

could you kindly give us the reasons of the difference between the two workflows mentioned above?

Thanks,
Andrea

**Comment by andrearendina** [comment]
Hi all,

do you have any feedback about this issue?

Thank you,
Andrea

**Comment by mpatrascoiu** [comment]
Hello Andrea,

I'd like to reproduce this issue.
Could I have a test location where I can try to upload a file?

Cheers,
Mihai

**Comment by mpatrascoiu** [comment]
Hello,

Trying on the endpoint you've sent me, I don't get the same behavior. Upload via both the `davs://` and `https://` schema works.

Can you reproduce the problem and send me your log files?
Before running the test:
1. Make sure to have `LOG_SENSITIVE=false` in `/etc/gfal2.d/http_plugin.conf`
2. Do you use macaroons? Default value is yes. Option is configured via `RETRIEVE_BEARER_TOKEN=true` in `/etc/gfal2.d/http_plugin.conf`

Example command:
```bash
$ gfal-copy -vvv --log-file=gfal2-issue16-davs.log check.sh davs://xs-606.cr.cnaf.infn.it:8443/muone-tape/test-andrea-2607
$ gfal-copy -vvv --log-file=gfal2-issue16-https.log check.sh https://xs-606.cr.cnaf.infn.it:8443/muone-tape/test-andrea-2608
```

Can you send me the log files from the above commands?

I see in your output that the `PROPFIND` command receives back an `HTTP 404` (expected, as file doesn't exist), but the `HEAD` command receives an `HTTP 403 Forbidden` response. I wouldn't be surprised if Gfal2 stops the upload here. However, on the test endpoint you've sent, I can't reproduce this behavior.

As a side note, `PROPFIND` should only be exercised over `davs://` protocol. Gfal2 exercises it as a courtesy also over `https://` in case it gets a positive answer. If it doesn't, it fallbacks to the `HEAD` request, where it receives `HTTP 403`.

Cheers,
Mihai

**Comment by andrearendina** [comment]
Hi Mihai,

thanks a lot for your clarifications.
To briefly summarise, I report here the reasons of the different workflows:

- When trying to upload via "https://" schema, Gfal2 does a PROPFIND looking for a positive result
- The server responds with 404 Not Found (expected behavior for a new file)
- Gfal2 falls back to HEAD request (if the schema were "davs://" this fallback wouldn't happen. On "https://" schema, there's no certainty the request was understood by the server)
- At this point, it should also receive 404 Not Found, but instead it receives HTTP 403
- A "Permission refused" error is non-retryable. Gfal2 will stop the operation as the credentials are not accepted

Also StoRM WebDAV developers confirmed that the HEAD methos is forbidden for write-only storage elements.

I close the ticket,
Andrea
