### ISSUE TITLE
dependencies not fully resolved for EL9/EPEL packages

### ISSUE THREAD

**Issue by thdesy** [cern-fts/gfal2#19]
Dear gfal2 developers,

on EL9 (Alma 9.3 flavoured) there seems to be a dependency missing on the python packages.

Installing from EPEL

- gfal2.x86_64 2.22.1-1.el9
- gfal2-all-2.22.1-1.el9.x86_64
- ...

does not pull the python packages, resulting in the tools fail with

```
Traceback (most recent call last):
  File "/usr/bin/gfal-ls", line 30, in <module>
    from gfal2_util.shell import Gfal2Shell
ModuleNotFoundError: No module named 'gfal2_util'
```

After a manual dep resolution installing `python3-gfal2 python3-gfal2-util`, the tools work as expected.

Probably the dependency on the python package is missing in the gfal2-packages?

Cheers,
  Thomas

**Comment by mpatrascoiu** [comment]
Hello Thomas,

There is no dependency missing at the Gfal2 level.
Gfal2 is a C/C++ library providing a low-level file access API.

Here is the `gfal2-all` requires:
```
%package all
Summary:            Meta package for GFAL 2.0 install
Requires:           %{name}%{?_isa} = %{version}-%{release}
Requires:           %{name}-plugin-file%{?_isa} = %{version}-%{release}
%if 0%{?rhel} == 7
Requires:           %{name}-plugin-lfc%{?_isa} = %{version}-%{release}
Requires:           %{name}-plugin-rfio%{?_isa} = %{version}-%{release}
%endif
Requires:           %{name}-plugin-dcap%{?_isa} = %{version}-%{release}
Requires:           %{name}-plugin-srm%{?_isa} = %{version}-%{release}
Requires:           %{name}-plugin-gridftp%{?_isa} = %{version}-%{release}
Requires:           %{name}-plugin-http%{?_isa} = %{version}-%{release}
Requires:           %{name}-plugin-xrootd%{?_isa} = %{version}-%{release}
Requires:           %{name}-plugin-sftp%{?_isa} = %{version}-%{release}
```

The Gfal2 tools you want are provided by the [gfal2-util](https://github.com/cern-fts/gfal2-util) project. This one relies on [gfal2-python](https://github.com/cern-fts/gfal2-python). Installing the Gfal2 tools will bring the required Gfal2 Python module (which in turn relies on the Gfal2 C/C++ library).

The correct way would be to install `python3-gfal2-util` (brings full stack for Gfal2 tools) + `gfal2-all` (to have all the Gfal2 plugins):
```bash
$ dnf install python3-gfal2-util gfal2-all
```

Hope this solves the question!

Cheers,
Mihai
